const constants = {
	MEDIAS: 'MEDIAS',
	SET_FILTER: 'MEDIAS_SET_FILTER',
	NEXT_PAGE: 'MEDIAS_NEXT_PAGE',
	FETCH: 'MEDIAS_FETCH',
	FETCH_FULFILLED: 'MEDIAS_FETCH_FULFILLED',
	FETCH_REJECTED: 'MEDIAS_FETCH_REJECTED',

	MOVIES: 'MOVIES',
	MOVIES_SELECTED: 'MOVIES_SELECTED',
	MOVIES_SET_FILTER: 'MOVIES_SET_FILTER',
	MOVIES_NEXT_PAGE: 'MOVIES_NEXT_PAGE',
	MOVIES_FETCH: 'MOVIES_FETCH',
	MOVIES_FETCH_FULFILLED: 'MOVIES_FETCH_FULFILLED',
	MOVIES_FETCH_REJECTED: 'MOVIES_FETCH_REJECTED',

	SERIES: 'SERIES',
	SERIES_SET_FILTER: 'SERIES_SET_FILTER',
	SERIES_FETCH: 'SERIES_FETCH',
	SERIES_FETCH_FULFILLED: 'SERIES_FETCH_FULFILLED',
	SERIES_FETCH_REJECTED: 'SERIES_FETCH_REJECTED',
};

export default constants;
