const constants = {
	LOGIN: 'USER_LOGIN',
	LOGGED_IN: 'USER_LOGGED_IN',
	LOGOUT: 'USER_LOGOUT',
	FETCH: 'FETCH_USER',
	FETCH_FULFILLED: 'FETCH_USER_FULFILLED',
	FETCH_REJECTED: 'FETCH_USER_REJECTED',
};
export default constants;
